# Generated by Django 4.0.5 on 2022-08-20 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(unique=True)),
                ('date_end', models.DateField(blank=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pay Period',
                'verbose_name_plural': 'Pay Periods',
                'ordering': ('-date_start',),
            },
        ),
        migrations.CreateModel(
            name='TimesheetShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(default='1')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='success_center_timesheets.payperiod')),
            ],
            options={
                'verbose_name': 'Timesheet Shift',
                'verbose_name_plural': 'Timesheet Shifts',
            },
        ),
        migrations.CreateModel(
            name='CurrentStepEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_and_cost_center', models.CharField(blank=True, max_length=10, null=True)),
                ('job_code', models.CharField(blank=True, max_length=25, null=True)),
                ('hours_per_pay_period', models.DecimalField(decimal_places=1, max_digits=4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Current Step Employee',
                'verbose_name_plural': 'Current Step Employees',
            },
        ),
    ]
