# Generated by Django 3.0.4 on 2020-03-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cae_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_row',
            field=models.BooleanField(null=True),
        ),
    ]
