# Generated by Django 3.0.5 on 2020-11-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cae_home', '0005_auto_20201014_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used for urls referencing this Software.', max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SoftwareDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_type', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'University'), (3, 'Research')], default=2)),
                ('version', models.CharField(max_length=255)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='Used for urls referencing this Software.', max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cae_home.Software')),
            ],
            options={
                'verbose_name': 'Software Detail',
                'verbose_name_plural': 'Software Details',
                'ordering': ('software__name', 'expiration', 'version'),
            },
        ),
    ]
