# Generated by Django 3.0.5 on 2021-07-21 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cae_home', '0008_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintermediary',
            name='last_ldap_check',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userintermediary',
            name='winno',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
