# Generated by Django 3.2.6 on 2021-08-31 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cae_home', '0010_auto_20210818_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userintermediary',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userintermediary',
            name='cae_is_active',
            field=models.BooleanField(default=True, help_text='Tracks if CAE LDAP says user is active.'),
        ),
        migrations.AddField(
            model_name='userintermediary',
            name='wmu_is_active',
            field=models.BooleanField(default=True, help_text='Tracks if WMU LDAP says user is active.'),
        ),
        migrations.AlterField(
            model_name='userintermediary',
            name='last_ldap_check',
            field=models.DateField(default=django.utils.timezone.now, help_text="Date of user's last sync with LDAP."),
        ),
    ]
