# Generated by Django 4.0.4 on 2022-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cae_home', '0011_auto_20210831_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemesterDate',
            new_name='Semester',
        ),
    ]
