# Generated by Django 3.0.5 on 2020-09-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cae_home', '0004_auto_20200403_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cae_home.WmuUser')),
            ],
            options={
                'verbose_name': 'Student Usage Log',
                'verbose_name_plural': 'Student Usage Logs',
            },
        ),
    ]
