# Generated by Django 4.0.5 on 2022-08-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('success_center_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=80, null=True)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_event', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutor Location',
                'verbose_name_plural': 'Tutor Locations',
            },
        ),
        migrations.AddField(
            model_name='studentusagelog',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentusagelog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='success_center_core.tutorlocations'),
        ),
    ]
